apiVersion: v1
kind: Pod
metadata:
  name: ready-http-pod
  labels:
    course: k8s-3.6.1
    date: 2023-01-05
spec:
  containers:
    - name: ready-http-c
      image: docker.io/library/nginx:1.22.1
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
  restartPolicy: Always
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
