apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-volume
  labels:
    course: k8s-3.6.3
    date: 2023-01-05
  annotations:
    auther: wangqiang
    addr: Beijing
spec:
  containers:
    - name: downwardapi-volume-c
      image: docker.io/library/ubuntu:22.04
      command: ["/bin/sh", "-c", "while [ true ]; do sleep 30; done"]
      volumeMounts:
        - name: dav
          mountPath: /downwardapi
  volumes:
    - name: dav
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
  restartPolicy: Never
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
