apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-env
  labels:
    course: k8s-3.6.1
    date: 2023-01-05
spec:
  containers:
    - name: downwardapi-env-c
      image: docker.io/library/ubuntu:22.04
      command: ["/bin/sh", "-c", "env && echo \"Hello, Hypnos\""]
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "1000m"
          memory: "1000Mi"
      env: 
        - name: POD_NAME 
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CPU_REQ
          valueFrom:
            resourceFieldRef:
              containerName: downwardapi-env-c
              resource: requests.cpu
        - name: MEMORY_LMT
          valueFrom:
            resourceFieldRef:
              containerName: downwardapi-env-c
              resource: limits.memory 

  restartPolicy: Never
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
